FLAGS = -O3 -mfpmath=sse -fstack-protector-all -g -W -Wall -Wextra -Wunused -Wcast-align -Werror -pedantic -pedantic-errors -Wfloat-equal -Wpointer-arith -Wformat-security -Wmissing-format-attribute -Wformat=1 -Wwrite-strings -Wcast-align -Wno-long-long -Woverloaded-virtual -Wnon-virtual-dtor -Wcast-qual -Wno-suggest-attribute=format
all: a.out
a.out:  list_arr.o
	g++ $(FLAGS) list_arr.o -o a.out 
list_arr.o: list_arr.cpp list_arr.h
	g++ $(FLAGS) -c list_arr.cpp

